# Generated by Django 5.2.1 on 2026-03-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used for seed/demo data)', max_length=500),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
