# Generated by Django 5.2.1 on 2026-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carimage_image_url_alter_carimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration_state',
            field=models.CharField(blank=True, help_text='e.g. GJ - Gujarat', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='sell_timeline',
            field=models.CharField(blank=True, help_text='When seller plans to sell', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MT', 'MT'), ('AT', 'AT')], max_length=20),
        ),
    ]
