# Generated by Django 5.2.1 on 2026-03-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_add_sell_timeline_registration_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External logo URL if image not uploaded', max_length=500),
        ),
    ]
