# Generated by Django 5.2.1 on 2026-03-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_add_brand_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo_url',
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ON_HOLD', 'On Hold'), ('SOLD', 'Sold')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MT', 'Manual'), ('AT', 'Auto')], max_length=20),
        ),
    ]
