# Generated by Django 5.2.1 on 2026-03-29 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_inquiry_is_read_car_unique_title_model_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year_to',
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'is_featured'], name='cars_car_status_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'created_at'], name='cars_car_status_created_idx'),
        ),
    ]
