# Generated by Django 5.2.1 on 2026-03-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_list_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='car',
            name='cars_car_status_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='cars_car_status_created_idx',
        ),
    ]
